POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name":"suresh",
    "email":"sureshnayak6695@gmail.com",
    "password":"Surya@413"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"sureshnayak6695@gmail.com",
    "password":"Surya@413"
}

###
GET http://localhost:3000/notes
###


GET http://localhost:3000/notes/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNDc0NjY0fQ.gvrZ3URsRe050WOjZjKVlD6phjW6RIFwkmgsxyn-G7w

###
POST http://localhost:3000/notes/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNDc0NjY0fQ.gvrZ3URsRe050WOjZjKVlD6phjW6RIFwkmgsxyn-G7w
{
    "title":"gym",
    "content":"leg day",
    "category":"workout"
}

###
PUT http://localhost:3000/notes/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNDc0NjY0fQ.gvrZ3URsRe050WOjZjKVlD6phjW6RIFwkmgsxyn-G7w

{
    "title":"Toor",
    "content":"enjoy holiday heartfully",
    "category":"toor"
}

###
DELETE http://localhost:3000/notes/10
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNDc0NjY0fQ.gvrZ3URsRe050WOjZjKVlD6phjW6RIFwkmgsxyn-G7w

###
DELETE http://localhost:3000/notes
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNDc0NjY0fQ.gvrZ3URsRe050WOjZjKVlD6phjW6RIFwkmgsxyn-G7w

###
PATCH http://localhost:3000/notes/12/pin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNDc0NjY0fQ.gvrZ3URsRe050WOjZjKVlD6phjW6RIFwkmgsxyn-G7w

{
  "pinned": true
}

###

PATCH http://localhost:3000/notes/12/archive
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNDc0NjY0fQ.gvrZ3URsRe050WOjZjKVlD6phjW6RIFwkmgsxyn-G7w

{
  "archived": true
}
